### ISSUE TITLE
[Feature request] Add requirements.txt

### ISSUE THREAD

**Issue by cakiki** [huggingface/education-toolkit#24]
It would be great to have a requirements file and/or a dockerfile for people who want to follow along a live tutorial session but don't want to use colab. 

I don't think the HF docker images include gradio and streamlit though.

**Comment by osanseviero** [comment]
cc @lewtun, WDYT? This seems quite simple, I think transformers, gradio, torch, and sentencepiece should be enough for it

**Comment by lewtun** [comment]
Sounds like a great idea to me! Would you like to open a PR for this @cakiki ? We could start with a simple `requirements.txt` file for now and just add an installation step in the README

**Comment by cakiki** [comment]
@lewtun I'll open a PR!
