### ISSUE TITLE
Education toolkit translation to Italian

### ISSUE THREAD

**Issue by omarespejel** [huggingface/education-toolkit#6]
Hi!

Let's bring the open-source education toolkit to all the Italian-speaking community :)

Who would want to translate? These are the files. If you want to translate any, let us know here.

- [x] `README.md`
- [x] `01_huggingface-hub-tour.md`
- [x] `02_ml-demos-with-gradio.ipynb`
- [x] `03_getting-started-with-transformers.ipynb`

Thanks!

**Comment by MorenoLaQuatra** [comment]
I'd try to start with the Italian language. I forked the repo here https://github.com/MorenoLaQuatra/education-toolkit .
I'll try to proceed step by step (I started by translating the first part of  01_huggingface-hub-tour.md). Is there any priority?

**Comment by omarespejel** [comment]
Hi @MorenoLaQuatra! Thanks! No priority.

Please let me know if you need anything.

Kind regards.

**Comment by omarespejel** [comment]
Hi @MorenoLaQuatra! I saw your fork already contains translations to several documents! That is great.

Feel free to make a PR mentioning this issue #6 when you feel ready 🤗

**Comment by MorenoLaQuatra** [comment]
Hi @omarespejel , I'll finish the translation in the next few days to complete tutorial 3, than for sure I'll open the PR, thanks!

**Comment by omarespejel** [comment]
@MorenoLaQuatra thank you!
